name: coverity

inputs:
  server-url: 
    description: 'Server URL'
    required: true
  api-token:  
    description: 'API token'
    required: true
  step_id:
    description: 'The ID of the step in the workflow'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Generate reference files 
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_TOKEN="${{ inputs.cloudbees_pat_token }}" \
          -e INPUT_CLOUDBEES_API_URL="${{ vars.cloudbees_api_url }}" \
          -e INPUT_RUN_ID="$GITHUB_RUN_ID" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="$GITHUB_RUN_ID" \
          -e GITHUB_WORKFLOW_REF="$GITHUB_WORKFLOW_REF" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:319c16869790d0d394ac6905d283209512b422b0 \
          generate-references --asset-type "CODE"

    - name: Print polaris conf
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          golang:latest \
          bash -c "chmod 777 /workspace/* && ls -al /workspace"
          # is it safe to set the permissions to 777?

    - name: Run coverity on polaris compliance plugin
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e RUN_ID="$GITHUB_RUN_ID" \
          -e JOB_ID="$GITHUB_JOB" \
          -e STEP_ID="${{ inputs.step_id }}" \
          -e POLARIS_SERVER_URL: ${{ inputs.server-url }}
          -e POLARIS_ACCESS_TOKEN: ${{ inputs.api-token }}
          public.ecr.aws/l7o7z1g8/actions/plugin-coverity-sca:5d56e78cf87dde7d7e31818cfba23df7012afbc2 \
          --mode single
          
    - name: Complete execution plan
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_TOKEN="${{ inputs.cloudbees_pat_token }}" \
          -e INPUT_CLOUDBEES_API_URL="${{ vars.cloudbees_api_url }}" \
          -e INPUT_RUN_ID="$GITHUB_RUN_ID" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="$GITHUB_RUN_ID" \
          -e GITHUB_WORKFLOW_REF="$GITHUB_WORKFLOW_REF" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:319c16869790d0d394ac6905d283209512b422b0 \
          process-outputs
